### ISSUE TITLE
using intake-xarray

### ISSUE THREAD

**Issue by aaronspring** [luke-gregor/dataBrewery#11]
Downloading somffn now works.
```python
# returns list of path
somffn = data_catalog.somffn.local_files(date_range)

# open as netcdf
somffn = xr.open_dataset(somffn[0],drop_variables='date')
```

The first line is dataBrewery. the last line could be nicely abstracted away with intake-xarray.
In the intake-xarray yaml file you can specify these kwargs like `drop_variables`. these kwargs are likely different for all dataset.
see https://gitlab.dkrz.de/m300524/pymistral/-/blob/master/intake/obs.yml:
```
    args:
      urlpath: '/work/mh0727/data/DUST/{{s_res}}_MAHOWALDDUST_{{version}}.nc'
      xarray_kwargs:
          decode_times: False
```
Maybe the intake-xarray yaml file can fetch its entries from your dataBrewery.yaml. Two yamls would be more annoying to maintain.
